### ISSUE TITLE
TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by LachlanArthur** [oklai/koala#385]
Just downloaded the app, I get this error every time I try to add a folder:
```
---uncaughtException---
TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at Object.exports.parseCompassConfig (C:\Program Files (x86)\Koala\app\scripts\projectSettings.js:222:28)
    at loadExistsProjectConfig (C:\Program Files (x86)\Koala\app\scripts\projectManager.js:208:32)
    at createProject (C:\Program Files (x86)\Koala\app\scripts\projectManager.js:70:26)
    at Object.exports.addProject (C:\Program Files (x86)\Koala\app\scripts\projectManager.js:29:19)
    at null._onTimeout (C:\Program Files (x86)\Koala\app\scripts\pages\main\project.js:40:28)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

Also, maybe make the error window resizable and the text selectable:
![Error message screenshot](http://i.imgur.com/KgqRGKQ.png)

**Comment by TholthoeunChansovann** [comment]
Hello u can write this Try cd %USERPROFILE% folder, and delete .koala folder.
