### ISSUE TITLE
Problem with ruby files

### ISSUE THREAD

**Issue by MSalehi** [oklai/koala#492]
Hi,
I'm using koala on ubuntu 15.04 and my ruby version is 2.1.2p95
when i've installed koala, i've tried to compile a simple sass file.
but it have an error and i don't know about this error.
here is my css generated by Koala and errors :
(i wrote line 1,2 and 3 to my sass file)
`
/*
Error: Invalid CSS after "red": expected expression (e.g. 1px, bold), was ";"
        on line 2 of /var/www/html/sass/style.sass

1: a{
2: 	color: red;
3: }

Backtrace:
/var/www/html/sass/style.sass:2
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/scss/parser.rb:1165:in `expected'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/script/lexer.rb:220:in `expected!'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/script/parser.rb:602:in `assert_done'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/script/parser.rb:63:in `parse'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/script/parser.rb:183:in `parse'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/script.rb:27:in `parse'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:1120:in `parse_script'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:710:in `parse_property'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:681:in `parse_property_or_rule'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:647:in `parse_line'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:525:in `build_tree'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:544:in `block in append_children'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:543:in `each'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:543:in `append_children'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:534:in `block in build_tree'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:527:in `each'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:527:in `build_tree'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:544:in `block in append_children'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:543:in `each'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:543:in `append_children'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:396:in `_to_tree'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/engine.rb:268:in `render'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/exec/sass_scss.rb:404:in `run'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/exec/sass_scss.rb:62:in `process_result'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/exec/base.rb:52:in `parse'
/usr/share/koala/rubygems/gems/sass-3.4.9/lib/sass/exec/base.rb:19:in `parse!'
/usr/share/koala/rubygems/gems/sass-3.4.9/bin/sass:13:in `<top (required)>'
/usr/share/koala/bin/sass:18:in `load'
/usr/share/koala/bin/sass:18:in `<main>'
*/
body:before {
  white-space: pre;
  font-family: monospace;
  content: "Error: Invalid CSS after \"red\": expected expression (e.g. 1px, bold), was \";\"\A         on line 2 of /var/www/html/sass/style.sass\A \A 1: a{\A 2: 	color: red;\A 3: }"; }

`

**Comment by MSalehi** [comment]
Sorry I’ve checked my file extension and turned it to .SCSS and problem goes away.
