### ISSUE TITLE
Throw an error after running

### ISSUE THREAD

**Issue by dingxiaoming521** [oklai/koala#726]
**Koala version**
2.3.0
**Bug report or feature request?**
Bug report

I download the installation package on the official website for installation, run error after installation。
the error info:
---error---
D:\Program Files (x86)\Koala\app\scripts\projectManager.js:494
Uncaught TypeError: Cannot read property 'options' of undefined

---uncaughtException---
TypeError: Cannot read property 'options' of undefined
    at creatFileObject (D:\Program Files (x86)\Koala\app\scripts\projectManager.js:494:81)
    at D:\Program Files (x86)\Koala\app\scripts\projectManager.js:249:27
    at Array.forEach (<anonymous>)
    at addFileItem (D:\Program Files (x86)\Koala\app\scripts\projectManager.js:247:14)
    at Object.exports.refreshProjectFileList (D:\Program Files (x86)\Koala\app\scripts\projectManager.js:136:5)
    at HTMLButtonElement.<anonymous> (D:\Program Files (x86)\Koala\app\scripts\pages\main\project.js:207:20)

---uncaughtException---
TypeError: Cannot read property 'compile' of undefined
    at Object.exports.compileFile (D:\Program Files\Koala\app\scripts\compilersManager.js:423:42)
    at autoCompileWhenAdded (D:\Program Files\Koala\app\scripts\projectManager.js:576:30)
    at Object.exports.addProject (D:\Program Files\Koala\app\scripts\projectManager.js:61:5)
    at Timeout._onTimeout (D:\Program Files\Koala\app\scripts\pages\main\project.js:40:28)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)

---uncaughtException---
TypeError: Cannot read property 'compile' of undefined
    at Object.exports.compileFile (D:\Program Files\Koala\app\scripts\compilersManager.js:423:42)
    at StatWatcher.<anonymous> (D:\Program Files\Koala\app\scripts\fileWatcher.js:206:44)
    at emitTwo (events.js:135:13)
    at StatWatcher.emit (events.js:224:7)
    at StatWatcher._handle.onchange (fs.js:1467:10)

---uncaughtException---
TypeError: Cannot read property 'compile' of undefined
    at Object.exports.compileFile (D:\Program Files\Koala\app\scripts\compilersManager.js:423:42)
    at StatWatcher.<anonymous> (D:\Program Files\Koala\app\scripts\fileWatcher.js:206:44)
    at emitTwo (events.js:135:13)
    at StatWatcher.emit (events.js:224:7)
    at StatWatcher._handle.onchange (fs.js:1467:10)

---uncaughtException---
TypeError: Cannot read property 'compile' of undefined
    at Object.exports.compileFile (D:\Program Files\Koala\app\scripts\compilersManager.js:423:42)
    at StatWatcher.<anonymous> (D:\Program Files\Koala\app\scripts\fileWatcher.js:206:44)
    at emitTwo (events.js:135:13)
    at StatWatcher.emit (events.js:224:7)
    at StatWatcher._handle.onchange (fs.js:1467:10)

---uncaughtException---
TypeError: Cannot read property 'compile' of undefined
    at Object.exports.compileFile (D:\Program Files\Koala\app\scripts\compilersManager.js:423:42)
    at StatWatcher.<anonymous> (D:\Program Files\Koala\app\scripts\fileWatcher.js:206:44)
    at emitTwo (events.js:135:13)
    at StatWatcher.emit (events.js:224:7)
    at StatWatcher._handle.onchange (fs.js:1467:10)

![112](https://user-images.githubusercontent.com/18361662/34979265-cc59dbf2-fadb-11e7-8427-b9da95ef5b88.png)
![113](https://user-images.githubusercontent.com/18361662/34979266-cc8a66a0-fadb-11e7-8e22-3fdb6afbddf7.png)
![114](https://user-images.githubusercontent.com/18361662/34979267-ccb5d150-fadb-11e7-8354-09e189613edd.png)
![115](https://user-images.githubusercontent.com/18361662/34979268-cce6a5aa-fadb-11e7-9dc3-fd8e9176b9c7.png)

**Comment by zaygraveyard** [comment]
I this the first time you install Koala on you machine?

**Comment by dingxiaoming521** [comment]
@zaygraveyard it's not the first. I uninstalled the previous version. and downloaded the latest version of the official website. After the installation is complete,it through the error.I am sure I have deleted all the relevant folders before reinstalling.

**Comment by zaygraveyard** [comment]
Can you delete `%USERPROFILE%\.koala` and try again?

**Comment by dingxiaoming521** [comment]
@zaygraveyard  I cleared all the related files in C disk, the problem still exists after reinstalling.

**Comment by zaygraveyard** [comment]
Does `%USERPROFILE%\.koala` exist and is not empty?
If so, can you paste the contents of `%USERPROFILE%\.koala\settings.json` here?

**Comment by dingxiaoming521** [comment]
@zaygraveyard  %USERPROFILE%\.koala is not empty and the file %USERPROFILE%\.koala\settings.json is show as below:
`
{
	"appVersion": "2.3.0",
	"ignores": [],
	"includePaths": [],
	"locales": "en_us",
	"minimizeToTray": true,
	"minimizeOnStartup": false,
	"notifyOnCompleted": false,
	"autoCompileOnAdd": true,
	"useCustomRuby": false,
	"rubyCommandPath": "",
	"compilers": {
		"compass": {
			"options": {},
			"advanced": {
				"useCompassCommand": false,
				"compassCommandPath": ""
			}
		}
	}
}
`

**Comment by dingxiaoming521** [comment]
`{
	"appVersion": "2.3.0",
	"ignores": [],
	"includePaths": [],
	"locales": "en_us",
	"minimizeToTray": true,
	"minimizeOnStartup": false,
	"notifyOnCompleted": false,
	"autoCompileOnAdd": true,
	"useCustomRuby": false,
	"rubyCommandPath": "",
	"compilers": {
		"compass": {
			"options": {},
			"advanced": {
				"useCompassCommand": false,
				"compassCommandPath": ""
			}
		}
	}
}`

**Comment by zaygraveyard** [comment]
Sorry normally removing `%USERPROFILE%\.koala`, uninstalling Koala using the uninstaller (`D:\Program Files\Koala\Uninstall Koala.exe`), then reinstalling it should fix the problem.
If it doesn't then I don't what could be causing these errors 😞

**Comment by dingxiaoming521** [comment]
@zaygraveyard  Still not available.

**Comment by dingxiaoming521** [comment]
@zaygraveyard  i uninstall it, and download the version 2.2.0 ,after installed can't found %USERPROFILE%\.koala and koala Can not run.From the Task Manager which can be seen just click after the start of operation, the process is over

**Comment by zaygraveyard** [comment]
You can try running Koala as administrator

**Comment by AgamlaRage** [comment]
I had another issue like this one. One day, Koala didn't wanted to run with this error
`C:/Program Files (x86)/Koala/app/scripts/patch.js cannot read property "appVersion" of null`

> Sorry normally removing %USERPROFILE%\.koala, uninstalling Koala using the uninstaller (D:\Program Files\Koala\Uninstall Koala.exe), then reinstalling it should fix the problem.
If it doesn't then I don't what could be causing these errors 😞

@zaygraveyard, your tricks worked for me.

**Comment by anjitpariyar** [comment]
and where does  %USERPROFILE%.koala  present?

**Comment by ziadkh0** [comment]
@anjitzero Open an explorer window and put `%USERPROFILE%\.koala` in the location bar, then press <kbd>enter</kbd>

**Comment by Islam-alshiki** [comment]
@zaygraveyard  Same proplem happen to me.
